version: '3'

services:
  openldap:
    container_name: openldap
    image: osixia/openldap:latest
    ports:
      - "389:389"
    environment:
      TZ: Asia/Tokyo
      LDAP_ORGANISATION: IBM
      LDAP_DOMAIN: instana.local
      LDAP_BASE_DN: dc=instana,dc=local
      LDAP_ADMIN_PASSWORD: admin
      LDAP_CONFIG_PASSWORD: config
      LDAP_TLS: false
    env_file: .env
    restart: always
    volumes:
      - ./ldapadd.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-ldapadd.ldif
    command: --copy-service
    networks:
      - instana

networks:
  instana:
    external: true
    name: instana